import Nav from '../components/Nav'
import './globals.css'


export const metadata = {
  title: 'PencilArt: Where Arts Comes To Life!',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true' />
        <link href="https://fonts.googleapis.com/css2?family=Righteous&family=Tilt+Prism&display=swap" rel="stylesheet" />
      </head>
      <body className='
      bg-backgroundPrimary
      '>
        <Nav />
        {children}

      </body>
    </html>
  )
}
